name: Generer velkomst-melding

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Sett opp Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer avhengigheter
        run: npm install

      - name: Kjør scriptet
        run: node velkomst.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          VOICE_ID: ${{ secrets.VOICE_ID }}

      - name: Commit og push mp3
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add velkomst.mp3
          git commit -m "Ny velkomst mp3" || echo "Ingen endringer å committe"
          git push
