name: Generer velkomst-melding

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3

      - name: Sett opp Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer avhengigheter
        run: npm install

      - name: Kjør script
        run: node velkomst.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          VOICE_ID: ${{ secrets.VOICE_ID }}

      - name: Last opp artefakt (mp3)
        uses: actions/upload-artifact@v3
        with:
          name: velkomst
          path: velkomst.mp3
